codecov:
  require_ci_to_pass: yes

ignore:
  - "app.py"
  - "app2.py"
  - "scoutbot/*/convert.py"
  - "scoutbot/*/convert.mvp.py"
  - "scoutbot/scoutbot.py"
  - "scoutbot/loc/transforms"
  - "scoutbot/scripts"

coverage:
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        target: 50%
  range: "50...90"
  round: down
  precision: 1

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
